# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1211, 731)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon/Snipaste_2023-04-18_22-26-28.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.Main_QW = QtWidgets.QWidget(MainWindow)
        self.Main_QW.setObjectName("Main_QW")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Main_QW)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_QF = QtWidgets.QFrame(self.Main_QW)
        self.Main_QF.setStyleSheet("QFrame#Main_QF{\n"
"background-color: rgb(46, 46, 46);\n"
"border:0px solid red;\n"
"border-radius:12px\n"
"}")
        self.Main_QF.setObjectName("Main_QF")
        self.main_qframe = QtWidgets.QHBoxLayout(self.Main_QF)
        self.main_qframe.setContentsMargins(0, 0, 0, 0)
        self.main_qframe.setSpacing(0)
        self.main_qframe.setObjectName("main_qframe")
        self.LeftMenuBg = QtWidgets.QFrame(self.Main_QF)
        self.LeftMenuBg.setMinimumSize(QtCore.QSize(68, 0))
        self.LeftMenuBg.setMaximumSize(QtCore.QSize(68, 16777215))
        self.LeftMenuBg.setStyleSheet("QFrame#LeftMenuBg{\n"
"background-color: rgba(255, 255, 255,0);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.LeftMenuBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenuBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenuBg.setObjectName("LeftMenuBg")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LeftMenuBg)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TopLogoInfo = QtWidgets.QFrame(self.LeftMenuBg)
        self.TopLogoInfo.setEnabled(True)
        self.TopLogoInfo.setMinimumSize(QtCore.QSize(0, 70))
        self.TopLogoInfo.setMaximumSize(QtCore.QSize(16777215, 70))
        self.TopLogoInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopLogoInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopLogoInfo.setObjectName("TopLogoInfo")
        self.logo = QtWidgets.QWidget(self.TopLogoInfo)
        self.logo.setGeometry(QtCore.QRect(10, 10, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(50, 50))
        self.logo.setMaximumSize(QtCore.QSize(50, 50))
        self.logo.setStyleSheet("border-image: url(:/img/icon/Snipaste_2023-04-18_22-26-28.png);\n"
"border:2px solid rgb(255, 255, 255);\n"
"border-radius:10px")
        self.logo.setObjectName("logo")
        self.Author = QtWidgets.QLabel(self.TopLogoInfo)
        self.Author.setGeometry(QtCore.QRect(90, 30, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Author.sizePolicy().hasHeightForWidth())
        self.Author.setSizePolicy(sizePolicy)
        self.Author.setMinimumSize(QtCore.QSize(60, 30))
        self.Author.setMaximumSize(QtCore.QSize(60, 30))
        self.Author.setStyleSheet("font: italic 11pt \"Segoe UI\";\n"
"color: rgba(255, 255, 255, 255);")
        self.Author.setAlignment(QtCore.Qt.AlignCenter)
        self.Author.setObjectName("Author")
        self.Title = QtWidgets.QLabel(self.TopLogoInfo)
        self.Title.setGeometry(QtCore.QRect(60, 10, 121, 20))
        self.Title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Title.setStyleSheet("font: 600 13pt \"Segoe UI Semibold\";\n"
"color: rgba(255, 255, 255, 255);")
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.verticalLayout_2.addWidget(self.TopLogoInfo)
        self.ToggleBox = QtWidgets.QFrame(self.LeftMenuBg)
        self.ToggleBox.setMinimumSize(QtCore.QSize(200, 80))
        self.ToggleBox.setMaximumSize(QtCore.QSize(200, 80))
        self.ToggleBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ToggleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ToggleBox.setObjectName("ToggleBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ToggleBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.ToggleBotton = QtWidgets.QPushButton(self.ToggleBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton.sizePolicy().hasHeightForWidth())
        self.ToggleBotton.setSizePolicy(sizePolicy)
        self.ToggleBotton.setMinimumSize(QtCore.QSize(0, 43))
        self.ToggleBotton.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.ToggleBotton.setFont(font)
        self.ToggleBotton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ToggleBotton.setMouseTracking(True)
        self.ToggleBotton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton.setAutoFillBackground(False)
        self.ToggleBotton.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 8px solid transparent;\n"
"text-align: center;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.ToggleBotton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icon/hamburger-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ToggleBotton.setIcon(icon1)
        self.ToggleBotton.setIconSize(QtCore.QSize(26, 24))
        self.ToggleBotton.setAutoDefault(False)
        self.ToggleBotton.setDefault(False)
        self.ToggleBotton.setFlat(False)
        self.ToggleBotton.setObjectName("ToggleBotton")
        self.horizontalLayout_19.addWidget(self.ToggleBotton)
        self.label_5 = QtWidgets.QLabel(self.ToggleBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_19.addWidget(self.label_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.verticalLayout_2.addWidget(self.ToggleBox)
        self.MenuBox = QtWidgets.QFrame(self.LeftMenuBg)
        self.MenuBox.setMinimumSize(QtCore.QSize(220, 0))
        self.MenuBox.setMaximumSize(QtCore.QSize(220, 16777215))
        self.MenuBox.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.MenuBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MenuBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuBox.setObjectName("MenuBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.MenuBox)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.fileButton_2 = QtWidgets.QPushButton(self.MenuBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileButton_2.sizePolicy().hasHeightForWidth())
        self.fileButton_2.setSizePolicy(sizePolicy)
        self.fileButton_2.setMinimumSize(QtCore.QSize(64, 43))
        self.fileButton_2.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.fileButton_2.setFont(font)
        self.fileButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fileButton_2.setMouseTracking(True)
        self.fileButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.fileButton_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.fileButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fileButton_2.setAutoFillBackground(False)
        self.fileButton_2.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 8px solid transparent;\n"
"text-align: center;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.fileButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icon/import_model.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileButton_2.setIcon(icon2)
        self.fileButton_2.setIconSize(QtCore.QSize(35, 30))
        self.fileButton_2.setAutoDefault(False)
        self.fileButton_2.setDefault(False)
        self.fileButton_2.setFlat(False)
        self.fileButton_2.setObjectName("fileButton_2")
        self.horizontalLayout_16.addWidget(self.fileButton_2)
        self.comboBox = QtWidgets.QComboBox(self.MenuBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setStyleSheet("QComboBox QAbstractItemView {\n"
"font-family: \"Microsoft YaHei\";\n"
"font-size: 13px;\n"
"background:rgba(200, 200, 200,150);\n"
"selection-background-color: rgba(200, 200, 200,50);\n"
"color: rgb(0, 255, 0);\n"
"outline:none;\n"
"border: 2px solid #42adff;\n"
"border-radius:6px;\n"
"\n"
"}\n"
"QComboBox{\n"
"font-family: \"Microsoft YaHei\";\n"
"font-size: 13px;\n"
"color: rgb(0, 255, 0);\n"
"border-width:0px;\n"
"border-color:white;\n"
"border-style:solid;\n"
"background-color: rgba(200, 200, 200,0);}\n"
"\n"
"QComboBox::drop-down {\n"
"margin-top:8;\n"
"height:20;\n"
"background:rgba(255,255,255,0);\n"
"border-image: url(:/img/icon/drop_white.png);\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(5)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.fileButton = QtWidgets.QPushButton(self.MenuBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileButton.sizePolicy().hasHeightForWidth())
        self.fileButton.setSizePolicy(sizePolicy)
        self.fileButton.setMinimumSize(QtCore.QSize(64, 43))
        self.fileButton.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.fileButton.setFont(font)
        self.fileButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fileButton.setMouseTracking(True)
        self.fileButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.fileButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.fileButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fileButton.setAutoFillBackground(False)
        self.fileButton.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left:8px solid transparent;\n"
"text-align: center;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.fileButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/icon/open_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileButton.setIcon(icon3)
        self.fileButton.setIconSize(QtCore.QSize(26, 24))
        self.fileButton.setAutoDefault(False)
        self.fileButton.setDefault(False)
        self.fileButton.setFlat(False)
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_20.addWidget(self.fileButton)
        self.label_6 = QtWidgets.QLabel(self.MenuBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_20.addWidget(self.label_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(5)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.cameraButton = QtWidgets.QPushButton(self.MenuBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraButton.sizePolicy().hasHeightForWidth())
        self.cameraButton.setSizePolicy(sizePolicy)
        self.cameraButton.setMinimumSize(QtCore.QSize(64, 43))
        self.cameraButton.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.cameraButton.setFont(font)
        self.cameraButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cameraButton.setMouseTracking(True)
        self.cameraButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cameraButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cameraButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cameraButton.setAutoFillBackground(False)
        self.cameraButton.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 8px solid transparent;\n"
"text-align: center;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.cameraButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/icon/camera_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cameraButton.setIcon(icon4)
        self.cameraButton.setIconSize(QtCore.QSize(26, 26))
        self.cameraButton.setAutoDefault(False)
        self.cameraButton.setDefault(False)
        self.cameraButton.setFlat(False)
        self.cameraButton.setObjectName("cameraButton")
        self.horizontalLayout_21.addWidget(self.cameraButton)
        self.label_7 = QtWidgets.QLabel(self.MenuBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_21.addWidget(self.label_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.cameraButton_2 = QtWidgets.QPushButton(self.MenuBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraButton_2.sizePolicy().hasHeightForWidth())
        self.cameraButton_2.setSizePolicy(sizePolicy)
        self.cameraButton_2.setMinimumSize(QtCore.QSize(64, 43))
        self.cameraButton_2.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.cameraButton_2.setFont(font)
        self.cameraButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cameraButton_2.setMouseTracking(True)
        self.cameraButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cameraButton_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cameraButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cameraButton_2.setAutoFillBackground(False)
        self.cameraButton_2.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 8px solid transparent;\n"
"text-align: center;\n"
"padding-left: 7px;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 15pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.cameraButton_2.setIconSize(QtCore.QSize(26, 26))
        self.cameraButton_2.setAutoDefault(False)
        self.cameraButton_2.setDefault(False)
        self.cameraButton_2.setFlat(False)
        self.cameraButton_2.setObjectName("cameraButton_2")
        self.horizontalLayout_17.addWidget(self.cameraButton_2)
        self.iouSpinBox = QtWidgets.QDoubleSpinBox(self.MenuBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iouSpinBox.sizePolicy().hasHeightForWidth())
        self.iouSpinBox.setSizePolicy(sizePolicy)
        self.iouSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.iouSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.iouSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 14px;\n"
"font-family: \"Microsoft YaHei UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/img/icon/箭头_列表展开.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/img/icon/箭头_列表展开.png);}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/img/icon/箭头_列表收起.png);}\n"
"QDoubleSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/img/icon/箭头_列表收起.png);}\n"
"")
        self.iouSpinBox.setMaximum(1.0)
        self.iouSpinBox.setSingleStep(0.01)
        self.iouSpinBox.setProperty("value", 0.45)
        self.iouSpinBox.setObjectName("iouSpinBox")
        self.horizontalLayout_17.addWidget(self.iouSpinBox)
        self.iouSlider = QtWidgets.QSlider(self.MenuBox)
        self.iouSlider.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(:/img/icon/circle.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 gray, stop:0.25 gray, stop:0.5 gray, stop:1 gray);                     \n"
"}")
        self.iouSlider.setMaximum(100)
        self.iouSlider.setProperty("value", 45)
        self.iouSlider.setOrientation(QtCore.Qt.Horizontal)
        self.iouSlider.setObjectName("iouSlider")
        self.horizontalLayout_17.addWidget(self.iouSlider)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(5)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.cameraButton_3 = QtWidgets.QPushButton(self.MenuBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraButton_3.sizePolicy().hasHeightForWidth())
        self.cameraButton_3.setSizePolicy(sizePolicy)
        self.cameraButton_3.setMinimumSize(QtCore.QSize(64, 43))
        self.cameraButton_3.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.cameraButton_3.setFont(font)
        self.cameraButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cameraButton_3.setMouseTracking(True)
        self.cameraButton_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cameraButton_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cameraButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cameraButton_3.setAutoFillBackground(False)
        self.cameraButton_3.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 8px solid transparent;\n"
"text-align: center;\n"
"padding-left: 6px;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 13pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.cameraButton_3.setIconSize(QtCore.QSize(26, 26))
        self.cameraButton_3.setAutoDefault(False)
        self.cameraButton_3.setDefault(False)
        self.cameraButton_3.setFlat(False)
        self.cameraButton_3.setObjectName("cameraButton_3")
        self.horizontalLayout_18.addWidget(self.cameraButton_3)
        self.confSpinBox = QtWidgets.QDoubleSpinBox(self.MenuBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confSpinBox.sizePolicy().hasHeightForWidth())
        self.confSpinBox.setSizePolicy(sizePolicy)
        self.confSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.confSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.confSpinBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.confSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 14px;\n"
"font-family: \"Microsoft YaHei UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/img/icon/箭头_列表展开.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/img/icon/箭头_列表展开.png);}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/img/icon/箭头_列表收起.png);}\n"
"QDoubleSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/img/icon/箭头_列表收起.png);}\n"
"")
        self.confSpinBox.setMaximum(1.0)
        self.confSpinBox.setSingleStep(0.01)
        self.confSpinBox.setProperty("value", 0.25)
        self.confSpinBox.setObjectName("confSpinBox")
        self.horizontalLayout_18.addWidget(self.confSpinBox)
        self.confSlider = QtWidgets.QSlider(self.MenuBox)
        self.confSlider.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(:/img/icon/circle.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 gray, stop:0.25 gray, stop:0.5 gray, stop:1 gray);                     \n"
"}")
        self.confSlider.setMaximum(100)
        self.confSlider.setProperty("value", 25)
        self.confSlider.setOrientation(QtCore.Qt.Horizontal)
        self.confSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.confSlider.setObjectName("confSlider")
        self.horizontalLayout_18.addWidget(self.confSlider)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.MenuBox)
        self.VersionInfo = QtWidgets.QFrame(self.LeftMenuBg)
        self.VersionInfo.setMinimumSize(QtCore.QSize(200, 10))
        self.VersionInfo.setMaximumSize(QtCore.QSize(200, 15))
        self.VersionInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VersionInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VersionInfo.setObjectName("VersionInfo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.VersionInfo)
        self.verticalLayout_3.setContentsMargins(18, 0, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.VersionLabel = QtWidgets.QLabel(self.VersionInfo)
        self.VersionLabel.setStyleSheet("font: 900 italic 10pt \"Segoe UI\";\n"
"color: rgba(255, 255, 255, 199);")
        self.VersionLabel.setText("")
        self.VersionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VersionLabel.setObjectName("VersionLabel")
        self.verticalLayout_3.addWidget(self.VersionLabel)
        self.verticalLayout_2.addWidget(self.VersionInfo)
        self.main_qframe.addWidget(self.LeftMenuBg)
        self.ContentBox = QtWidgets.QFrame(self.Main_QF)
        self.ContentBox.setStyleSheet("QFrame#ContentBox{\n"
"background-color:rgb(245, 245, 245);\n"
"border:0px solid red;\n"
"border-radius:12px\n"
"}")
        self.ContentBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ContentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ContentBox.setObjectName("ContentBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ContentBox)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.top = QtWidgets.QFrame(self.ContentBox)
        self.top.setMinimumSize(QtCore.QSize(0, 30))
        self.top.setMaximumSize(QtCore.QSize(16777215, 30))
        self.top.setStyleSheet("QFrame#top{\n"
"background-color: rgba(255, 255, 255,0);\n"
"}")
        self.top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.explain_title = QtWidgets.QLabel(self.top)
        self.explain_title.setMinimumSize(QtCore.QSize(0, 30))
        self.explain_title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.explain_title.setStyleSheet("font: 700 italic 11pt \"Segoe UI\";")
        self.explain_title.setText("")
        self.explain_title.setAlignment(QtCore.Qt.AlignCenter)
        self.explain_title.setObjectName("explain_title")
        self.horizontalLayout.addWidget(self.explain_title)
        self.buttons_sf = QtWidgets.QFrame(self.top)
        self.buttons_sf.setMinimumSize(QtCore.QSize(120, 30))
        self.buttons_sf.setMaximumSize(QtCore.QSize(120, 30))
        self.buttons_sf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_sf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_sf.setObjectName("buttons_sf")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttons_sf)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minButton = QtWidgets.QPushButton(self.buttons_sf)
        self.minButton.setMinimumSize(QtCore.QSize(38, 33))
        self.minButton.setMaximumSize(QtCore.QSize(38, 33))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(19)
        self.minButton.setFont(font)
        self.minButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"margin-bottom:8px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.minButton.setIconSize(QtCore.QSize(27, 29))
        self.minButton.setObjectName("minButton")
        self.horizontalLayout_2.addWidget(self.minButton)
        self.max_sf = QtWidgets.QPushButton(self.buttons_sf)
        self.max_sf.setMinimumSize(QtCore.QSize(38, 33))
        self.max_sf.setMaximumSize(QtCore.QSize(38, 33))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(20)
        self.max_sf.setFont(font)
        self.max_sf.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"margin-bottom:8px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.max_sf.setIconSize(QtCore.QSize(27, 29))
        self.max_sf.setObjectName("max_sf")
        self.horizontalLayout_2.addWidget(self.max_sf)
        self.closeButton = QtWidgets.QPushButton(self.buttons_sf)
        self.closeButton.setMinimumSize(QtCore.QSize(38, 28))
        self.closeButton.setMaximumSize(QtCore.QSize(38, 28))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(20)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.horizontalLayout.addWidget(self.buttons_sf)
        self.verticalLayout_6.addWidget(self.top)
        self.content = QtWidgets.QFrame(self.ContentBox)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_5.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.main_content = QtWidgets.QVBoxLayout()
        self.main_content.setSpacing(5)
        self.main_content.setObjectName("main_content")
        self.char_label = QtWidgets.QLabel(self.content)
        self.char_label.setMinimumSize(QtCore.QSize(0, 20))
        self.char_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.char_label.setFont(font)
        self.char_label.setStyleSheet("padding-left:12px;")
        self.char_label.setObjectName("char_label")
        self.main_content.addWidget(self.char_label)
        self.QF_Group = QtWidgets.QFrame(self.content)
        self.QF_Group.setMinimumSize(QtCore.QSize(0, 100))
        self.QF_Group.setMaximumSize(QtCore.QSize(16777215, 100))
        self.QF_Group.setStyleSheet("QFrame#QF_Group{\n"
"background-color: rgb(238, 242, 255);\n"
"border:2px solid rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"}")
        self.QF_Group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QF_Group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QF_Group.setObjectName("QF_Group")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.QF_Group)
        self.horizontalLayout_3.setContentsMargins(-1, 9, -1, 15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fps_label = QtWidgets.QLabel(self.QF_Group)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.fps_label.setFont(font)
        self.fps_label.setObjectName("fps_label")
        self.horizontalLayout_3.addWidget(self.fps_label)
        self.main_content.addWidget(self.QF_Group)
        self.Result_QF = QtWidgets.QFrame(self.content)
        self.Result_QF.setStyleSheet("")
        self.Result_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Result_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Result_QF.setObjectName("Result_QF")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.Result_QF)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.splitter = QtWidgets.QSplitter(self.Result_QF)
        self.splitter.setStyleSheet("#splitter::handle{background: 1px solid  rgba(200, 200, 200,100);}")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.raw_video = QtWidgets.QLabel(self.splitter)
        self.raw_video.setMinimumSize(QtCore.QSize(200, 100))
        self.raw_video.setStyleSheet("background-color: rgb(238, 242, 255);\n"
"border:2px solid rgb(255, 255, 255);\n"
"border-radius:15px;")
        self.raw_video.setText("")
        self.raw_video.setAlignment(QtCore.Qt.AlignCenter)
        self.raw_video.setObjectName("raw_video")
        self.out_video = QtWidgets.QLabel(self.splitter)
        self.out_video.setMinimumSize(QtCore.QSize(200, 100))
        self.out_video.setStyleSheet("background-color: rgb(238, 242, 255);\n"
"border:2px solid rgb(255, 255, 255);\n"
"border-radius:15px")
        self.out_video.setText("")
        self.out_video.setAlignment(QtCore.Qt.AlignCenter)
        self.out_video.setObjectName("out_video")
        self.verticalLayout_16.addWidget(self.splitter)
        self.main_content.addWidget(self.Result_QF)
        self.Pause_QF = QtWidgets.QFrame(self.content)
        self.Pause_QF.setMinimumSize(QtCore.QSize(0, 30))
        self.Pause_QF.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Pause_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Pause_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Pause_QF.setObjectName("Pause_QF")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Pause_QF)
        self.horizontalLayout_4.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.runButton = QtWidgets.QPushButton(self.Pause_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setMinimumSize(QtCore.QSize(44, 30))
        self.runButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);\n"
"}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.runButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/icon/pause_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/img/icon/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap(":/img/icon/pause_black.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.runButton.setIcon(icon5)
        self.runButton.setIconSize(QtCore.QSize(30, 30))
        self.runButton.setCheckable(True)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_4.addWidget(self.runButton)
        self.progressBar = QtWidgets.QProgressBar(self.Pause_QF)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 8))
        self.progressBar.setStyleSheet("QProgressBar{ color: rgb(255, 255, 255); font:12pt; border-radius:2px; text-align:center; border:none; background-color: rgba(215, 215, 215,100);} \n"
"QProgressBar:chunk{ border-radius:0px; background: rgba(55, 55, 55, 200);}")
        self.progressBar.setMaximum(1000)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.stopButton = QtWidgets.QPushButton(self.Pause_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(44, 32))
        self.stopButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);\n"
"}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.stopButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/icon/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon6)
        self.stopButton.setIconSize(QtCore.QSize(32, 34))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_4.addWidget(self.stopButton)
        self.saveCheckBox = QtWidgets.QCheckBox(self.Pause_QF)
        self.saveCheckBox.setStyleSheet("\n"
"QCheckBox\n"
"{font-size: 16px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(    255,0,0);;}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/img/icon/button-off.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    image: url(:/img/icon/button-on.png);\n"
"}\n"
"")
        self.saveCheckBox.setChecked(True)
        self.saveCheckBox.setObjectName("saveCheckBox")
        self.horizontalLayout_4.addWidget(self.saveCheckBox)
        self.main_content.addWidget(self.Pause_QF)
        self.horizontalLayout_5.addLayout(self.main_content)
        self.groupBox = QtWidgets.QGroupBox(self.content)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("#groupBox{\n"
"background-color: rgb(46, 46, 46);\n"
"border: 0px solid #42adff;\n"
"border-left: 0px solid #d9d9d9;\n"
"border-right: 0px solid rgba(29, 83, 185, 255);\n"
"border-radius:12px;\n"
"margin-top:26px;\n"
"color: rgb(255, 255, 255);\n"
"padding-top:20px;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setContentsMargins(2, -1, 9, -1)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem1)
        self.result_btn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_btn.sizePolicy().hasHeightForWidth())
        self.result_btn.setSizePolicy(sizePolicy)
        self.result_btn.setMinimumSize(QtCore.QSize(28, 36))
        self.result_btn.setMaximumSize(QtCore.QSize(28, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.result_btn.setFont(font)
        self.result_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.result_btn.setMouseTracking(True)
        self.result_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.result_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.result_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_btn.setAutoFillBackground(False)
        self.result_btn.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 10px solid transparent;\n"
"text-align: center;\n"
"margin-left: -10px;\n"
"color: rgba(255, 255, 255, 199);\n"
"border-image: url(:/img/icon/hamburger-button.png);\n"
"font: 700 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.result_btn.setText("")
        self.result_btn.setIconSize(QtCore.QSize(26, 25))
        self.result_btn.setAutoDefault(False)
        self.result_btn.setDefault(False)
        self.result_btn.setFlat(False)
        self.result_btn.setObjectName("result_btn")
        self.verticalLayout_7.addWidget(self.result_btn)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(64, 16777215))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.resultWidget = QtWidgets.QListWidget(self.groupBox)
        self.resultWidget.setStyleSheet("QListWidget{\n"
"background-color: rgba(12, 28, 77, 0);\n"
"border: 1px solid rgba(200, 200, 200,100);\n"
"border-bottom: 0px solid rgba(200, 200, 200,100);\n"
"border-radius:10px;\n"
"font-family: \"Microsoft YaHei\";\n"
"font-size: 16px;\n"
"margin-top:20px;\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.resultWidget.setWordWrap(True)
        self.resultWidget.setObjectName("resultWidget")
        self.horizontalLayout_6.addWidget(self.resultWidget)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_6.addWidget(self.content)
        self.below = QtWidgets.QFrame(self.ContentBox)
        self.below.setMinimumSize(QtCore.QSize(0, 30))
        self.below.setMaximumSize(QtCore.QSize(16777215, 30))
        self.below.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.below.setFrameShadow(QtWidgets.QFrame.Raised)
        self.below.setObjectName("below")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.below)
        self.horizontalLayout_13.setContentsMargins(20, 2, 0, 4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.statistic_label = QtWidgets.QLabel(self.below)
        self.statistic_label.setStyleSheet("font: 700 11pt \"Segoe UI\";\n"
"color: rgba(0, 0, 0, 140);")
        self.statistic_label.setObjectName("statistic_label")
        self.horizontalLayout_13.addWidget(self.statistic_label)
        self.frame_size_grip = QtWidgets.QFrame(self.below)
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_size_grip.setStyleSheet("border-radius:30px;")
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_13.addWidget(self.frame_size_grip)
        self.verticalLayout_6.addWidget(self.below)
        self.main_qframe.addWidget(self.ContentBox)
        self.verticalLayout.addWidget(self.Main_QF)
        MainWindow.setCentralWidget(self.Main_QW)

        self.retranslateUi(MainWindow)
        self.result_btn.clicked.connect(MainWindow.close_result) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Author.setText(_translate("MainWindow", "BOX"))
        self.Title.setText(_translate("MainWindow", "Function"))
        self.label_5.setText(_translate("MainWindow", " HideMenu"))
        self.comboBox.setItemText(0, _translate("MainWindow", "yolov5s.pt"))
        self.comboBox.setItemText(1, _translate("MainWindow", "yolov5x.pt"))
        self.label_6.setText(_translate("MainWindow", "Select Video File"))
        self.label_7.setText(_translate("MainWindow", "Select Camera"))
        self.cameraButton_2.setText(_translate("MainWindow", "IoU"))
        self.cameraButton_3.setText(_translate("MainWindow", "ConF"))
        self.minButton.setText(_translate("MainWindow", "0"))
        self.max_sf.setText(_translate("MainWindow", "1"))
        self.closeButton.setText(_translate("MainWindow", "r"))
        self.char_label.setText(_translate("MainWindow", "Detection-Based-YOLOv5"))
        self.fps_label.setText(_translate("MainWindow", "FPS"))
        self.saveCheckBox.setText(_translate("MainWindow", "save automatically"))
        self.groupBox.setTitle(_translate("MainWindow", "Result"))
        self.statistic_label.setText(_translate("MainWindow", "Welcome!"))
import apprcc_rc
